num_wires: 4
depth: 3
scheme: 'full'
embed_type: 'zz'
block_type: 'conv'
num_processor: 1
num_obs: 1
out_dim: 2

batch_size: 250
data_dim: 4
num_epoch: 50
shuffle_per_epoch: true

dataset_path: ' '
save_to: './test'
