num_wires: 12
depth: 5
scheme: 'cyclic'
num_processor: 3
num_obs: 3
out_dim: 2

batch_size: 500
num_epoch: 50
shuffle_per_epoch: true

dataset_path: './Dataset_12dim_large'
save_to: 'scheme_12cyclic'

