num_wires: 4
depth: 3
scheme: 'cross'
embed_type: 'amp'
block_type: 'conv'
num_processor: 2
num_obs: 2
out_dim: 2

batch_size: 500
data_dim: 8
num_epoch: 50
shuffle_per_epoch: true

dataset_path: ' '
save_to: './test'
